# Generated by Django 3.1.13 on 2021-11-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_anonymousmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousmessage',
            name='message',
            field=models.CharField(max_length=5000, null=True, verbose_name='message'),
        ),
    ]
