# Generated by Django 3.1.13 on 2021-11-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_anonymousmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousmessage',
            name='message',
        ),
    ]
